### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by MarkStega** [BBGONE/JRIApp#2]
With the references fixed I can now build RIAppDemo. However, I get an error from IIS when I try to run the app:

Config Error	   Cannot read configuration file
Config File	   \\?\C:\DATA\GIT\JRIApp\DEMOS\RIAppDemoMVC\RIAppDemo\web.config

My app is actually in d:\solutions\temporary solutions\jriapp

**Comment by BBGONE** [comment]
Probably the config file is locked by some process.
I tried to remove my local copy of repository and recloned it again.
After that i  copied it all to another directory, opened it in Visual Studio 2015 and 
then pressed F5 (to run it). No problem - all worked as expected.
You can try to run it without debugging (Ctrl - F5).  It works on my computer too.

**Comment by MarkStega** [comment]
With a repeat reclone/build/run it now runs; I haven't installed the adventureworks db so the data queries fail as expected. I am most interested in the client side TS though so I am good to go. You might consider adding a .gitignore to the project and rebuilding the repository. I've attached my typical gitignore.
[.gitignore.zip](https://github.com/BBGONE/JRIApp/files/289471/default.gitignore.zip)

**Comment by BBGONE** [comment]
Thanks very much for the gitignore. I thought previously about adding it, but did not add it at the start.
I think the project carried with it temporary files in .vs (VS 2015 adds it) directory which i finally deleted.
If the solution is not rebuilt in the whole, there are files left from my on builds.
Maybe it caused the problem.
P.S. I have a local dev. edition SQL Server where i attached the adventure works DB. It is good for different purposes - i can do tests on it with new features.
