### ISSUE TITLE
multi windows

### ISSUE THREAD

**Issue by cbsistem** [BBGONE/JRIApp#3]
helo  
is posible create example to open multiple windows , style mdi forms .??
tanks

**Comment by BBGONE** [comment]
Hello. I'm not vouching that i will do quickly (i don't need it for my apps, so i will try to create example when i have nothing to do else).
**But I think the best way to do it is to reuse this** http://fstoke.me/jquery/window/
The content can be a template (like i do when a modal dialog is shown) or the content can be an IFRAME to separate window contents completely.
